# Generated by Django 4.2.7 on 2026-08-19 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(db_index=True, max_length=60, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=25)),
                ('gestational_weeks', models.IntegerField(default=12, help_text='Current gestational age in weeks')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('blood_group', models.CharField(blank=True, default='O+', max_length=10)),
                ('gravida', models.IntegerField(default=1, help_text='Total number of pregnancies')),
                ('para', models.IntegerField(default=0, help_text='Number of viable births')),
                ('medical_history', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('hemoglobin', models.FloatField()),
                ('blood_pressure', models.IntegerField()),
                ('systolic_bp', models.IntegerField(blank=True, null=True)),
                ('diastolic_bp', models.IntegerField(blank=True, null=True)),
                ('sugar_level', models.FloatField()),
                ('protein_intake', models.FloatField()),
                ('body_temp', models.FloatField(blank=True, null=True)),
                ('heart_rate', models.IntegerField(blank=True, null=True)),
                ('predicted_risk', models.CharField(choices=[('Low Risk', 'Low Risk'), ('Mid Risk', 'Mid Risk'), ('High Risk', 'High Risk')], max_length=30)),
                ('risk_level_code', models.IntegerField(default=0)),
                ('confidence_score', models.FloatField(help_text='Percentage confidence')),
                ('risk_distribution', models.JSONField(default=dict, help_text='Class probabilities dictionary')),
                ('clinical_flags', models.JSONField(default=list, help_text='Triggered clinical warning flags')),
                ('dietary_recommendations', models.JSONField(default=list, help_text='Generated dietary recommendations')),
                ('assessed_features', models.JSONField(blank=True, default=dict)),
                ('doctor_notes', models.TextField(blank=True, default='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_assessments', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='patients.patientprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
